version: '3.9'

services:
  mysql:
    hostname: quick_crm_mysql
    container_name: quick_crm_mysql
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWD}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'quick_crm_mysql']
      timeout: 5s
      retries: 5
    volumes:
      - quick_crm_mysql:/var/lib/mysql
    networks:
      - quick_crm_network
  php:
    container_name: quick_crm_php
    hostname: quick_crm_php
    build:
      context: .
      dockerfile: docker-compose/php/Dockerfile
    volumes:
      - ./:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    networks:
      - quick_crm_network
    depends_on:
      mysql:
        condition: service_healthy
  nginx:
    hostname: quick_crm_nginx
    container_name: quick_crm_nginx
    image: nginx:alpine
    ports:
      - ${APP_PORT}:80
    expose:
      - 80
      - 8000
    networks:
      - quick_crm_network
    volumes:
      - ./:/var/www/html/
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  quick_crm_mysql:
    driver: local
    name: quick_crm_mysql

networks:
  quick_crm_network:
    driver: bridge
    name: quick_crm_network