version: '3.9'

services:
  mysql:
    container_name: quick_crm_mysql
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWD}
    volumes:
      - quick_crm_mysql:/var/lib/mysql
    networks:
      - quick_crm_network

volumes:
  quick_crm_mysql:
    driver: local
    name: quick_crm_mysql

networks:
  quick_crm_network:
    driver: bridge
    name: quick_crm_network